-- TABLA -1 EXTERNA
CREATE TABLE CLIENTE(
	ID BIGSERIAL,
	ID_RAPPI VARCHAR(80) NOT NULL,
	TIPO_ID VARCHAR(8) NOT NULL,
	IDENTIFICACION VARCHAR(100) NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE NOT NULL,
	FECHA_CREACION TIMESTAMP NOT NULL,	
	USUARIO_CREACION VARCHAR(70) NOT NULL,
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);
ALTER TABLE CLIENTE ADD CONSTRAINT "PK_CLIENTE" PRIMARY KEY (ID);
ALTER TABLE CLIENTE ADD CONSTRAINT "UK_CLIENTE_RPP" UNIQUE (ID_RAPPI);
ALTER TABLE CLIENTE ADD CONSTRAINT "UK_CLIENTE" UNIQUE (TIPO_ID,IDENTIFICACION);


--CRUD tabla 2
CREATE TABLE TIPO_CONCEPTO(
	ID SERIAL,
	ID_CONCEPTO  VARCHAR(3) NOT NULL,
	ID_CONCEPTO_RAPPI VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE NOT NULL,
	FECHA_CREACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(70) NOT NULL,
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);

ALTER TABLE TIPO_CONCEPTO ADD CONSTRAINT "PK_TIPO_CONCEPTO" PRIMARY KEY (ID);

--CRUD tabla 3
CREATE TABLE SEGMENTO(
	ID SERIAL,
	COD_SEGMENTO VARCHAR(10) NOT NULL,
	COD_SEGMENTO_RAPPI VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE NOT NULL,
	FECHA_CREACION TIMESTAMP NOT NULL,	
	USUARIO_CREACION VARCHAR(70) NOT NULL,
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);
ALTER TABLE SEGMENTO ADD CONSTRAINT "PK_SEGMENTO" PRIMARY KEY (ID);

--CRUD tabla 5
CREATE TABLE COEFICIENTE(
	ID SERIAL,
	CODIGO_COEFICIENTE VARCHAR(10),
	COD_SEGMENTO INTEGER,
	VALOR_T	NUMERIC(8,5),
	ACTIVO BOOLEAN DEFAULT TRUE,	
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);
ALTER TABLE COEFICIENTE ADD CONSTRAINT "PK_COEFICIENTE" PRIMARY KEY (ID);
ALTER TABLE COEFICIENTE ADD CONSTRAINT "FK_COEFICIENTE_SEGMENT" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);

-- Deberia tener periodo? - tablas 7
-- Se remueve TIPO_ID, IDENT. Fk cliente(id_rappi
CREATE TABLE CAL_EXTERNA(
	ID BIGSERIAL,
	ID_RAPPI VARCHAR(80) NOT NULL,
	NUMERO_TARJETA VARCHAR(150),
	CAL_SUBJETIVA VARCHAR(8),
	MOTIVO_DESC VARCHAR(250),
	CODIGO_LEY VARCHAR(30),
	ACTIVO	BOOLEAN,
	FECHA_CORTE DATE,	
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70)	
);
ALTER TABLE CAL_EXTERNA ADD CONSTRAINT "PK_CAL_EXTERNA" PRIMARY KEY (ID);
ALTER TABLE CAL_EXTERNA ADD CONSTRAINT "FK_CALEXT_CLIENT" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);


--CRUD TABLA 8
CREATE TABLE PRO_INCUMPLIMIENTO(
	ID SERIAL,
	COD_SEGMENTO INTEGER,
	TIPO_MATRIZ	VARCHAR(2),
	CALIFICACION	VARCHAR(5),
	FACTOR DOUBLE precision,
	ACTIVO BOOLEAN DEFAULT TRUE,	
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);
ALTER TABLE PRO_INCUMPLIMIENTO ADD CONSTRAINT "PK_PRO_INCUMPLIMIENTO" PRIMARY KEY (ID);
ALTER TABLE PRO_INCUMPLIMIENTO ADD CONSTRAINT "FK_PROINCUMPL_SEGMENT" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);

-- CRUD tabla 6
CREATE TABLE CALIFICACION_RANGOS(
	ID SERIAL,
	COD_SEGMENTO INTEGER,
	PUNTAJE_INF DOUBLE precision,
	PUNTAJE_SUP DOUBLE precision,
	CALIFICACION VARCHAR(4),
	ACTIVO BOOLEAN DEFAULT TRUE,	
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);
ALTER TABLE CALIFICACION_RANGOS ADD CONSTRAINT "PK_CALIFICACION_RANGOS" PRIMARY KEY (ID);
ALTER TABLE CALIFICACION_RANGOS ADD CONSTRAINT "FK_CALRANG_SEGMENT" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);

-- tabla 10 
-- Se remueve TIPO_ID, IDENT. Fk cliente(id_rappi) 
-- PENDIENTE CAMBIAR FECHA
CREATE TABLE MORA_CLIENTE(
	ID BIGSERIAL,
	FECHA_CORTE DATE,
	ID_RAPPI VARCHAR(80) NOT NULL,
	NUMERO_TARJETA VARCHAR(150),
	DIAS_MORA INTEGER,
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70)
);
ALTER TABLE MORA_CLIENTE ADD CONSTRAINT "PK_MORA_CLIENTE" PRIMARY KEY (ID);
ALTER TABLE MORA_CLIENTE ADD CONSTRAINT "FK_MORCLIEN_CLIENT" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);

--TABLA 4
-- Se remueve TIPO_ID, IDENT. Fk cliente(id_rappi) 
-- PENDIENTE CAMBIAR FECHA
CREATE TABLE VECTOR_MORAS(
	ID BIGSERIAL,
	FECHA_CORTE_ANIO INTEGER,
	FECHA_CORTE_MES INTEGER,
	ID_RAPPI VARCHAR(80) NOT NULL,
	AMB	INTEGER,
	AMC INTEGER,
	MMB	INTEGER,
	MMC INTEGER,
	MMD	INTEGER,
	CRB VARCHAR(30),
	GI VARCHAR(30),
	CAR VARCHAR(30),
	CAM VARCHAR(30),
	PR VARCHAR(30),
	HIPOTECA VARCHAR(30),
	PREPAGO VARCHAR(30),
	FECHA_CORTE DATE
);
ALTER TABLE VECTOR_MORAS ADD CONSTRAINT "PK_VECT_MORA" PRIMARY KEY (ID);
ALTER TABLE VECTOR_MORAS ADD CONSTRAINT "UK_VECT_MORA" UNIQUE (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI);
ALTER TABLE VECTOR_MORAS ADD CONSTRAINT "FK_VECTMORA_CLIENT" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);

--TABLA 4.1
-- Se remueve TIPO_ID, IDENT. Fk cliente(id_rappi) 
-- PENDIENTE CAMBIAR FECHA
CREATE TABLE VECTOR_MORAS_H(
	ID BIGSERIAL,
	FECHA_CORTE_ANIO INTEGER,
	FECHA_CORTE_MES INTEGER,
	ID_RAPPI VARCHAR(80) NOT NULL,
	AMB	INTEGER,
	AMC INTEGER,
	MMB	INTEGER,
	MMC INTEGER,
	MMD	INTEGER,
	CRB VARCHAR(30),
	GI VARCHAR(30),
	CAR VARCHAR(30),
	CAM VARCHAR(30),
	PR VARCHAR(30),
	HIPOTECA VARCHAR(30),
	PREPAGO VARCHAR(30),
	FECHA_CORTE DATE
)PARTITION BY LIST (FECHA_CORTE_ANIO);


--PARTICION 2020
CREATE TABLE VECTOR_MORAS_H2020 PARTITION OF VECTOR_MORAS_H FOR VALUES IN (2020) ;
CREATE INDEX ON VECTOR_MORAS_H2020 (FECHA_CORTE_ANIO);
ALTER TABLE VECTOR_MORAS_H2020 ADD CONSTRAINT "PK_VECT_MORA_H20" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON VECTOR_MORAS_H2020 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI);
ALTER TABLE VECTOR_MORAS_H2020 ADD CONSTRAINT "FK_VECTMORAH_CLIENT20" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);

--PARTICION 2021
CREATE TABLE VECTOR_MORAS_H2021 PARTITION OF VECTOR_MORAS_H FOR VALUES IN (2021) ;
CREATE INDEX ON VECTOR_MORAS_H2021 (FECHA_CORTE_ANIO);
ALTER TABLE VECTOR_MORAS_H2021 ADD CONSTRAINT "PK_VECT_MORA_H21" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON VECTOR_MORAS_H2021 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI);
ALTER TABLE VECTOR_MORAS_H2021 ADD CONSTRAINT "FK_VECTMORAH_CLIENT21" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);

--PARTICION 2022
CREATE TABLE VECTOR_MORAS_H2022 PARTITION OF VECTOR_MORAS_H FOR VALUES IN (2022) ;
CREATE INDEX ON VECTOR_MORAS_H2022 (FECHA_CORTE_ANIO);
ALTER TABLE VECTOR_MORAS_H2022 ADD CONSTRAINT "PK_VECT_MORA_H22" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON VECTOR_MORAS_H2022 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI);
ALTER TABLE VECTOR_MORAS_H2022 ADD CONSTRAINT "FK_VECTMORAH_CLIENT22" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);

--PARTICION 2023
CREATE TABLE VECTOR_MORAS_H2023 PARTITION OF VECTOR_MORAS_H FOR VALUES IN (2023) ;
CREATE INDEX ON VECTOR_MORAS_H2023 (FECHA_CORTE_ANIO);
ALTER TABLE VECTOR_MORAS_H2023 ADD CONSTRAINT "PK_VECT_MORA_H23" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON VECTOR_MORAS_H2023 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI);
ALTER TABLE VECTOR_MORAS_H2023 ADD CONSTRAINT "FK_VECTMORAH_CLIENT23" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);



--TABLA 1
-- Se remueve TIPO_ID, IDENT. Fk cliente(id_rappi) 
CREATE TABLE CALC_MENSUAL_TC(
	ID BIGSERIAL,
	FECHA_CORTE_ANIO INTEGER,
	FECHA_CORTE_MES INTEGER,
	ID_RAPPI VARCHAR(80) NOT NULL,
	NUM_TARJETA VARCHAR(120),
	TIPO_CONCEPTO VARCHAR(5),
	SALDO_CONCEPTO DOUBLE precision,
	DIAS_MORA	INTEGER,
	TIPO_GARANTIA VARCHAR(10),
	VALOR_GARANTIA DOUBLE precision,
	COD_SEGMENTO	INTEGER, --FK
	CAL_MRCO	VARCHAR(5),
	CAL_RIESGO	VARCHAR(5),
	CAL_RESTRUCTURACION VARCHAR(5),
	CAL_DEFINITIVA VARCHAR(5),
	VAL_PROV_INDI DOUBLE precision,
	VAL_PROCICLICO DOUBLE precision,
	VAL_CONTRACICLICO DOUBLE precision,
	VAR_PROCICLICO DOUBLE precision,
	VAR_CONTRACICLICO DOUBLE precision,
	GAS_PROCICLICO DOUBLE precision,
	GAS_CONTRACICLICO DOUBLE precision,
	REC_PROCICLICO DOUBLE precision,
	REC_CONTRACICLICO DOUBLE precision,
	CCO_PROCICLICO VARCHAR(80),
	CCO_CONTRACICLICO VARCHAR(80),
	CCG_PROCICLICO VARCHAR(80),
	CCG_CONTRACICLICO VARCHAR(80),
	CCR_PROCICLICO VARCHAR(80),
	CCR_CONTRACICLICO VARCHAR(80),
	FECHA_CORTE DATE,
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);
ALTER TABLE CALC_MENSUAL_TC ADD CONSTRAINT "PK_CALCMENS" PRIMARY KEY (ID);
ALTER TABLE CALC_MENSUAL_TC ADD CONSTRAINT "UK_CALCMENS" UNIQUE (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI,NUM_TARJETA,TIPO_CONCEPTO,TIPO_GARANTIA);
ALTER TABLE CALC_MENSUAL_TC ADD CONSTRAINT "FK_CALCMENS_CLIENT" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);
ALTER TABLE CALC_MENSUAL_TC ADD CONSTRAINT "FK_CALCMENS_SEGMENT" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);


--TABLA 1.1
-- Se remueve TIPO_ID, IDENT. Fk cliente(id_rappi) 
-- PENDIENTE CAMBIAR FECHA
CREATE TABLE CALC_MENSUAL_TC_H(
	ID BIGSERIAL,
	FECHA_CORTE_ANIO INTEGER,
	FECHA_CORTE_MES INTEGER,
	ID_RAPPI VARCHAR(80) NOT NULL,
	NUM_TARJETA VARCHAR(120),
	TIPO_CONCEPTO VARCHAR(5),
	SALDO_CONCEPTO DOUBLE precision,
	DIAS_MORA	INTEGER,
	TIPO_GARANTIA VARCHAR(10),
	VALOR_GARANTIA DOUBLE precision,
	COD_SEGMENTO	INTEGER, --FK
	CAL_MRCO	VARCHAR(5),
	CAL_RIESGO	VARCHAR(5),
	CAL_RESTRUCTURACION VARCHAR(5),
	CAL_DEFINITIVA VARCHAR(5),
	VAL_PROV_INDI DOUBLE precision,
	VAL_PROCICLICO DOUBLE precision,
	VAL_CONTRACICLICO DOUBLE precision,
	VAR_PROCICLICO DOUBLE precision,
	VAR_CONTRACICLICO DOUBLE precision,
	GAS_PROCICLICO DOUBLE precision,
	GAS_CONTRACICLICO DOUBLE precision,
	REC_PROCICLICO DOUBLE precision,
	REC_CONTRACICLICO DOUBLE precision,
	CCO_PROCICLICO VARCHAR(80),
	CCO_CONTRACICLICO VARCHAR(80),
	CCG_PROCICLICO VARCHAR(80),
	CCG_CONTRACICLICO VARCHAR(80),
	CCR_PROCICLICO VARCHAR(80),
	CCR_CONTRACICLICO VARCHAR(80),
	FECHA_CORTE DATE,
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
)PARTITION BY LIST (FECHA_CORTE_ANIO);

CREATE TABLE CALC_MENSUAL_TC_H2020 PARTITION OF CALC_MENSUAL_TC_H FOR VALUES IN (2020) ;
CREATE INDEX ON CALC_MENSUAL_TC_H2020 (FECHA_CORTE_ANIO);
ALTER TABLE CALC_MENSUAL_TC_H2020 ADD CONSTRAINT "PK_CALCMENS_H20" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON CALC_MENSUAL_TC_H2020 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI,NUM_TARJETA,TIPO_CONCEPTO,TIPO_GARANTIA);
ALTER TABLE CALC_MENSUAL_TC_H2020 ADD CONSTRAINT "FK_CALCMENSH_CLIENT20" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);
ALTER TABLE CALC_MENSUAL_TC_H2020 ADD CONSTRAINT "FK_CALCMENSH_SEGMENT20" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);

CREATE TABLE CALC_MENSUAL_TC_H2021 PARTITION OF CALC_MENSUAL_TC_H FOR VALUES IN (2021) ;
CREATE INDEX ON CALC_MENSUAL_TC_H2021 (FECHA_CORTE_ANIO);
ALTER TABLE CALC_MENSUAL_TC_H2021 ADD CONSTRAINT "PK_CALCMENS_H21" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON CALC_MENSUAL_TC_H2021 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI,NUM_TARJETA,TIPO_CONCEPTO,TIPO_GARANTIA);
ALTER TABLE CALC_MENSUAL_TC_H2021 ADD CONSTRAINT "FK_CALCMENSH_CLIENT21" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);
ALTER TABLE CALC_MENSUAL_TC_H2021 ADD CONSTRAINT "FK_CALCMENSH_SEGMENT21" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);

CREATE TABLE CALC_MENSUAL_TC_H2022 PARTITION OF CALC_MENSUAL_TC_H FOR VALUES IN (2022) ;
CREATE INDEX ON CALC_MENSUAL_TC_H2022 (FECHA_CORTE_ANIO);
ALTER TABLE CALC_MENSUAL_TC_H2022 ADD CONSTRAINT "PK_CALCMENS_H22" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON CALC_MENSUAL_TC_H2022 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI,NUM_TARJETA,TIPO_CONCEPTO,TIPO_GARANTIA);
ALTER TABLE CALC_MENSUAL_TC_H2022 ADD CONSTRAINT "FK_CALCMENSH_CLIENT22" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);
ALTER TABLE CALC_MENSUAL_TC_H2022 ADD CONSTRAINT "FK_CALCMENSH_SEGMENT22" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);

CREATE TABLE CALC_MENSUAL_TC_H2023 PARTITION OF CALC_MENSUAL_TC_H FOR VALUES IN (2023) ;
CREATE INDEX ON CALC_MENSUAL_TC_H2023 (FECHA_CORTE_ANIO);
ALTER TABLE CALC_MENSUAL_TC_H2023 ADD CONSTRAINT "PK_CALCMENS_H23" PRIMARY KEY (ID);
CREATE UNIQUE INDEX ON CALC_MENSUAL_TC_H2023 (FECHA_CORTE_ANIO,FECHA_CORTE_MES,ID_RAPPI,NUM_TARJETA,TIPO_CONCEPTO,TIPO_GARANTIA);
ALTER TABLE CALC_MENSUAL_TC_H2023 ADD CONSTRAINT "FK_CALCMENSH_CLIENT23" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);
ALTER TABLE CALC_MENSUAL_TC_H2023 ADD CONSTRAINT "FK_CALCMENSH_SEGMENT23" FOREIGN KEY (COD_SEGMENTO) REFERENCES SEGMENTO(ID);


--TABLA 9  --CRUD
CREATE TABLE TIPO_GARANTIA(
	ID SERIAL,
	cod_grantia VARCHAR(5),
	DESCRIPCION VARCHAR(80),
	DAI	INTEGER,
	PDI_DAI	DOUBLE precision,
	DDI	INTEGER,
	PDI_DDI DOUBLE precision,
	DDII DOUBLE precision,
	PDI_DDII DOUBLE precision,
	ACTIVO BOOLEAN DEFAULT TRUE,	
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(70)
);
ALTER TABLE TIPO_GARANTIA ADD CONSTRAINT "PK_TIPO_GARANTIA" PRIMARY KEY (ID);
ALTER TABLE TIPO_GARANTIA ADD CONSTRAINT "UK_TIPO_GARANTIA" UNIQUE (COD_GRANTIA);

--CRUD TABLA 11
CREATE TABLE CONCEPTO_CALIFICACION(
	ID SERIAL,
	TIPO_CONCEPTO VARCHAR(5),
	CALIFICACION_DEF VARCHAR(5),
	CUENTA_CIP VARCHAR(80),
	CUENTA_CIC VARCHAR(80),
	CUENTA_GASTO_CIP VARCHAR(80),
	CUENTA_GASTO_CIC VARCHAR(80),
	CUENTA_RECU_CIP VARCHAR(80),
	CUENTA_RECU_CIC VARCHAR(80),
	ACTIVO BOOLEAN DEFAULT TRUE,	
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(80),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(80)
);
ALTER TABLE CONCEPTO_CALIFICACION ADD CONSTRAINT "PK_CONCEPTO_CALIFICACION" PRIMARY KEY (ID);

--CRUD TABLA CUENTAS ORDEN
CREATE TABLE CUENTAS_ORDEN(
	ID SERIAL,
	TIPO_CONCEPTO VARCHAR(5),
	CUENTA_CRED VARCHAR(80),
	CUENTA_DEB VARCHAR(80),
	DIAS_INI	INT,
	DIAS_FIN	INT,
	ACTIVO BOOLEAN DEFAULT TRUE,	
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(80),
	FECHA_MODIFICACION TIMESTAMP,	
	USUARIO_MODIFICACION VARCHAR(80)
);
ALTER TABLE CUENTAS_ORDEN ADD CONSTRAINT "PK_CUENTAS_ORDEN" PRIMARY KEY (ID);

CREATE TABLE CALFICACION_VS(
	ID BIGSERIAL,
	FECHA_CORTE DATE,
	ID_RAPPI VARCHAR(80) NOT NULL,
	DIAS_MORA INT,
	DIAS_MORA_ANT INT,
	TIPO_CONCEPTO VARCHAR(30),
	CALFICACION_ANT VARCHAR(30),
	CALIFICACION_ACT VARCHAR(30),
	SALDO_CONCEPTO DOUBLE precision,
	VAR_SALDO DOUBLE precision,
	COMPO_IND_PRO DOUBLE precision,
	COMPO_IND_CON DOUBLE precision,	
	GASTO_PRO DOUBLE precision,
	GASTO_CON DOUBLE precision,
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70)
);

ALTER TABLE CALFICACION_VS ADD CONSTRAINT "PK_CALFICACION_VS" PRIMARY KEY (ID);
ALTER TABLE CALFICACION_VS ADD CONSTRAINT "FK_CAL_VS_TO_PERSON" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);

CREATE TABLE COMPROBANTE_CONT(
	ID BIGSERIAL,
	FECHA_CORTE DATE,
	ID_RAPPI VARCHAR(80) NOT NULL,
	TIPO_CONCEPTO VARCHAR(30),
	NUM_CUENTA_CONT_DEB VARCHAR(80),
	NUM_CUENTA_CONT_CRE VARCHAR(80),
	VAL_DEBITO DOUBLE precision,
	VAL_CREDITO DOUBLE precision,
	CAL_DEFINITIVA  VARCHAR(30),
	TIPO VARCHAR(30),
	FECHA_CREACION TIMESTAMP,	
	USUARIO_CREACION VARCHAR(70)
);
ALTER TABLE COMPROBANTE_CONT ADD CONSTRAINT "PK_COMPROBANTE_CONT" PRIMARY KEY (ID);
ALTER TABLE COMPROBANTE_CONT ADD CONSTRAINT "FK_COMPROBANTE_TO_PERSON" FOREIGN KEY (ID_RAPPI) REFERENCES CLIENTE(ID_RAPPI);

CREATE TABLE CARGA_TMP(
	ID_RAPPI VARCHAR(120) NOT NULL,
	INFO	JSON NOT NULL
);

ALTER TABLE CARGA_TMP ADD CONSTRAINT "PK_CARGA_TMP" PRIMARY KEY (ID_RAPPI);



CREATE TABLE CARGA_ARCHIVO(
	ID_RESUMEN BIGSERIAL,
	REGISTROS_CARGADOS BIGINT,
	REGISTRO_ERRADOS BIGINT,
	TOTAL_REGISTRO BIGINT,
	NAME_FILE VARCHAR(70),
	ESTADO VARCHAR(70),
	IDJOB BIGINT,
	INICIO TIMESTAMP,
	FINALIZO TIMESTAMP
);
ALTER TABLE CARGA_ARCHIVO ADD CONSTRAINT "PK_CARGA_ARCHIVO" PRIMARY KEY (ID_RESUMEN);


CREATE TABLE REPORTE_SALDO_CARGUE(
	ID BIGSERIAL,
	IDJOB BIGINT,
	saldo_Deuda DOUBLE precision,
	saldo_Mora DOUBLE precision,
	saldo_Interes_Corriente DOUBLE precision,
	saldo_Interes_Mora DOUBLE precision,
	saldo_Otro_Cargo DOUBLE precision,
	saldo_Otro_Concepto DOUBLE precision	
);

ALTER TABLE REPORTE_SALDO_CARGUE ADD CONSTRAINT "PK_REPORTESALDOCAR" PRIMARY KEY (ID);



CREATE TABLE PROCESS_DATA_INFO(
	ID BIGSERIAL,
	CLIENTES_PROCESADOS BIGINT,
	REGISTROS_ERRADOS BIGINT,
	TOTAL_REGISTRO BIGINT,
	ESTADO VARCHAR(70),
	IDJOB BIGINT,
	FECHA_CORTE DATE,
	INICIO TIMESTAMP,
	FINALIZO TIMESTAMP
);
ALTER TABLE PROCESS_DATA_INFO ADD CONSTRAINT "PK_PROCESS_DATA_INFO" PRIMARY KEY (ID);

CREATE TABLE CONTABILIDAD_RESUMEN(
	ID BIGSERIAL,
	CUENTA_CONTABLE VARCHAR(70),
	VALOR  DOUBLE precision,
	TIPO_CUENTA VARCHAR(70),
    ID_PROCESS_DATA BIGINT
);

ALTER TABLE CONTABILIDAD_RESUMEN ADD CONSTRAINT "PK_CONTABILIDAD_RESUMEN" PRIMARY KEY (ID);
ALTER TABLE CONTABILIDAD_RESUMEN	 ADD CONSTRAINT "FK_CONT_RES_PROCESS" FOREIGN KEY (ID_PROCESS_DATA) REFERENCES PROCESS_DATA_INFO(ID);

CREATE TABLE FLUJO(
	ID BIGSERIAL,
	ESTADO_APP VARCHAR(70),
	ID_PROCESO BIGINT,
	ID_CARGUE BIGINT,
	FINALIZO boolean default false
);
ALTER TABLE FLUJO ADD CONSTRAINT "PK_FLUJO" PRIMARY KEY (ID);

CREATE TABLE FLUJO_CAL_EXT(
	ID BIGSERIAL,
	ESTADO_APP VARCHAR(70),	
	FECHA_CORTE DATE,
	FINALIZO boolean default false
);
ALTER TABLE FLUJO_CAL_EXT ADD CONSTRAINT "PK_FLUJO_CAL_EXT" PRIMARY KEY (ID);

CREATE TABLE PARAMS(
	KEY_PARAM VARCHAR(20),	
	VALUE_PARAM VARCHAR(60),
	DESC_PARAM VARCHAR(200)
);

ALTER TABLE PARAMS ADD CONSTRAINT "PK_PARAMS" PRIMARY KEY (KEY_PARAM);